GET http://localhost:3001/api/notes

### 
GET http://localhost:3001/api/notes/636239eaccfc6a58ba0452df

### 
GET http://localhost:3001/api/notes/999

### 
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Lalilalal", 
    "important": true
}

### 
PUT http://localhost:3001/api/notes/63625ab5938402179d75d7fb
Content-Type: application/json

{
    "content": "Lalilalal", 
    "important": false
}

### 
PUT http://localhost:3001/api/notes/6362477f2e86dc87efbfbf65
Content-Type: application/json

{
    "content": "Whoops that was a spelling mistake", 
    "important": true
}

### 
DELETE http://localhost:3001/api/notes/636239f3c806dc84108d6621